runtime: nodejs20
env: standard

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "20"

env_variables:
    UPLOAD_PATH: /mnt/disks/storage/uploads

handlers:
  - url: /client/dist
    static_dir: dist

  